---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deps.klink.dev
  resources:
  - workloaddependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deps.klink.dev
  resources:
  - workloaddependencies/finalizers
  verbs:
  - update
- apiGroups:
  - deps.klink.dev
  resources:
  - workloaddependencies/status
  verbs:
  - get
  - patch
  - update
