//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependsOnEntry) DeepCopyInto(out *DependsOnEntry) {
	*out = *in
	out.Condition = in.Condition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependsOnEntry.
func (in *DependsOnEntry) DeepCopy() *DependsOnEntry {
	if in == nil {
		return nil
	}
	out := new(DependsOnEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCondition) DeepCopyInto(out *HealthCondition) {
	*out = *in
	out.Window = in.Window
	out.RecoveryWindow = in.RecoveryWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCondition.
func (in *HealthCondition) DeepCopy() *HealthCondition {
	if in == nil {
		return nil
	}
	out := new(HealthCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifySpec) DeepCopyInto(out *NotifySpec) {
	*out = *in
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.OnPhases != nil {
		in, out := &in.OnPhases, &out.OnPhases
		*out = make([]DependencyPhase, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifySpec.
func (in *NotifySpec) DeepCopy() *NotifySpec {
	if in == nil {
		return nil
	}
	out := new(NotifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnDegradedSpec) DeepCopyInto(out *OnDegradedSpec) {
	*out = *in
	out.MaxSuspendDuration = in.MaxSuspendDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnDegradedSpec.
func (in *OnDegradedSpec) DeepCopy() *OnDegradedSpec {
	if in == nil {
		return nil
	}
	out := new(OnDegradedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependency) DeepCopyInto(out *WorkloadDependency) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependency.
func (in *WorkloadDependency) DeepCopy() *WorkloadDependency {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadDependency) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependencyList) DeepCopyInto(out *WorkloadDependencyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependencyList.
func (in *WorkloadDependencyList) DeepCopy() *WorkloadDependencyList {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependencyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadDependencyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependencySpec) DeepCopyInto(out *WorkloadDependencySpec) {
	*out = *in
	out.Dependent = in.Dependent
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]DependsOnEntry, len(*in))
		copy(*out, *in)
	}
	out.OnDegraded = in.OnDegraded
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(NotifySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependencySpec.
func (in *WorkloadDependencySpec) DeepCopy() *WorkloadDependencySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependencyStatus) DeepCopyInto(out *WorkloadDependencyStatus) {
	*out = *in
	if in.SavedReplicas != nil {
		in, out := &in.SavedReplicas, &out.SavedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.DegradedSince != nil {
		in, out := &in.DegradedSince, &out.DegradedSince
		*out = (*in).DeepCopy()
	}
	if in.SuspendedAt != nil {
		in, out := &in.SuspendedAt, &out.SuspendedAt
		*out = (*in).DeepCopy()
	}
	if in.HealthySince != nil {
		in, out := &in.HealthySince, &out.HealthySince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependencyStatus.
func (in *WorkloadDependencyStatus) DeepCopy() *WorkloadDependencyStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependencyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
