//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependsOnEntry) DeepCopyInto(out *DependsOnEntry) {
	*out = *in
	out.Condition = in.Condition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependsOnEntry.
func (in *DependsOnEntry) DeepCopy() *DependsOnEntry {
	if in == nil {
		return nil
	}
	out := new(DependsOnEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCondition) DeepCopyInto(out *HealthCondition) {
	*out = *in
	out.Window = in.Window
	out.RecoveryWindow = in.RecoveryWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCondition.
func (in *HealthCondition) DeepCopy() *HealthCondition {
	if in == nil {
		return nil
	}
	out := new(HealthCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnDegradedSpec) DeepCopyInto(out *OnDegradedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnDegradedSpec.
func (in *OnDegradedSpec) DeepCopy() *OnDegradedSpec {
	if in == nil {
		return nil
	}
	out := new(OnDegradedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependency) DeepCopyInto(out *WorkloadDependency) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependency.
func (in *WorkloadDependency) DeepCopy() *WorkloadDependency {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadDependency) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependencyList) DeepCopyInto(out *WorkloadDependencyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependencyList.
func (in *WorkloadDependencyList) DeepCopy() *WorkloadDependencyList {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependencyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadDependencyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependencySpec) DeepCopyInto(out *WorkloadDependencySpec) {
	*out = *in
	out.Dependent = in.Dependent
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]DependsOnEntry, len(*in))
		copy(*out, *in)
	}
	out.OnDegraded = in.OnDegraded
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependencySpec.
func (in *WorkloadDependencySpec) DeepCopy() *WorkloadDependencySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDependencyStatus) DeepCopyInto(out *WorkloadDependencyStatus) {
	*out = *in
	if in.SavedReplicas != nil {
		in, out := &in.SavedReplicas, &out.SavedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.DegradedSince != nil {
		in, out := &in.DegradedSince, &out.DegradedSince
		*out = (*in).DeepCopy()
	}
	if in.HealthySince != nil {
		in, out := &in.HealthySince, &out.HealthySince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDependencyStatus.
func (in *WorkloadDependencyStatus) DeepCopy() *WorkloadDependencyStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadDependencyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
