name: Tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    name: Build and vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...
